### ISSUE TITLE
Проверка ДЗ

### ISSUE THREAD

**Issue by IrkaTyman** [liminfinity/shri-infra-homework#7]
1. Флоу на ПР 
1.1. lint и test выполняются не параллельно из-за того что являются шагами процесса. Можно разнести на разные процессы:
```
lint:
    runs-on: ubuntu-latest
    steps:
      ***
test:
    runs-on: ubuntu-latest
    steps:
          ***
```
1.2. cancel_merge будто бы не нужен, хватит настроек гитхаба для запрета на мердж

2. Флоу на Релиз
2.1. lint и test выполняются не параллельно из-за того что являются шагами процесса
